name: racco_final
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.7.0
  http: ^0.13.6
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.2.19
  loading_animation_widget: ^1.2.0+4
  iconly: ^1.0.1
  url_launcher: ^6.1.11
  flutter_session_manager: ^1.0.3
  connectivity_plus: ^4.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.5
  onesignal_flutter: ^5.0.0
  cached_network_image: ^3.2.3
  animated_custom_dropdown: ^1.5.0
  permission_handler: ^10.4.5
  firebase_core: ^2.15.1
  step_progress_indicator: ^1.0.2
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/LOGO-NewEraConnect.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/imgs/LOGO-NewEraConnect.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/imgs/LOGO-NewEraConnect.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/imgs/LOGO-NewEraConnect.png" 

flutter: 
  uses-material-design: true


  assets:
    - assets/imgs/ 

